### ISSUE TITLE
change all tabs to 4 x spaces

### ISSUE THREAD

**Issue by shoulders** [disorganised-mess/startpage#1]
This is my prefered method and is part of the PSR code rules.

Spaces are much better because unlike tabs, they always show the same indentations.

**Comment by disorganised-mess** [comment]
This is more about personal preference than technical merit.
PSR code rules have to do with PHP and considering there is no PHP present here I don't feel those rules apply. Were it PHP, then I would adhere to that standard.
Tabs for me are more efficient, though I appreciate the suggestion.

**Comment by disorganised-mess** [comment]
I use Kate as my main text editor. Formatting looks great there, but I did look at it in the online editor here and the tabs do look really horrible. However, I'm not likely to change it simply because I don't use any sort of online editor. Kate allows for setting of the number of spaces in indentation which is set to 4 characters.

**Comment by shoulders** [comment]
One of the main reasons for using spaces is the formatting issue. Also languages like YAML rely on spacing for the indentations.

My text editor is notepad++ and my IDE of choice is Netbeans 9.0.

**P.S.** startpage is very useful either way, thanks

**Comment by disorganised-mess** [comment]
Glad you find the page useful. Made it to be simple and effective, didn't want to wade through all my bookmarks for the things that really need to be accessed daily.
I'll consider this matter closed.
